config/routes.rb
Rails.application.routes.draw do
  
  get 'home/new' => 'home#new'
  post 'home' => 'home#create'
  get 'relationships/followings'
  get 'relationships/followers'
  
  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: "home#index"
 
  resources :posts, only: [:create, :new, :edit, :update, :destroy]
  resources :users, only: :show
  resource :profile, only: %i[show edit update]
  
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  scope '(:locale)' do
    resources :books
    resources :users, except: :create do
      member do
        get :followings, :followers
      end
    end
    resource :user_avatars, only: :destroy
    resources :relationships, only: %I[create destroy] # 追記
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

    def edit
      @user = User.find(current_user.id)
    end
    
    def update
      @user = User.find(current_user.id)
      if @user.update(user_params)
        redirect_to "/users/#{current_user.id}", success: "ユーザーを更新しました"
      else
        flash.now['danger'] = "ユーザーを更新できませんでした"
        render :edit 
      end
    end
    
    def show
      @profile = User.find(parms[:id])
    end
    
    private
    
    def user_params
      params.require(:user).permit(:email, :nickname, :avatar)
    end
    
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<!DOCTYPE html>
<html>
  <body>
    <main class="bg-home">
      <% content_for(:title, 'プロフィール編集') %>
      <div class="container pt-3">
        <div class="row">
          <div class="col-md-10 offset-md-1 mb-5">
            <h1 class="float-left"><%= t('.プロフィール編集') %></h1>
          </div>
          <div class="col-md-10 offset-md-1">
            <%= form_with model: @user, url: profile_path, local: true do |f| %>
              <div class="form-group">
                <%= f.label :Eメール %>
                <%= f.email_field :email, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :ニックネーム %>
                <%= f.text_field :nickname, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :画像 %>
                <%= f.file_field :avatar, class: "form-control", accept: 'image/*', onchange: 'previewFileWithId(preview)' %>
                <%= f.hidden_field :avatar_cache %>
                <div class='mt-3 mb-3'>
                  <%= image_tag @user.avatar.url , size: '100x100', class: 'rounded-circle' %>
                </div>
              </div>
              <%= f.submit "更新", defaults:"update", class: "btn btn-primary"%>
            <% end %>  
          </div>
        </div>
      </div>
    </main>

app/views/profiles/show.html.erb
  <body>
    <main class="bg-home">
      <!--ログイン本人のマイページ-->
      <%- if current_user.try(:id) == current_user(:id) %>
      <p><%= @current_user.email %>さんのページ</p>
      <% content_for(:title, 'プロフィール') %>
      <div class="container pt-3">
        <div class="row">
          <div class="col-md-10 offset-md-1 mb-5">
            <h1 class="float-left"><%= t('.プロフィール') %></h1>
            <%=link_to "編集", edit_profile_path, class: 'btn btn-success float-right' %>
            </div>
            <div class="col-md-10 offset-md-1">
              <table class="table">
                <tbody>
                  <tr>
                    <th>
                      <span>メールアドレス</span>
                    </th>
                    <td><%= current_user.email %></td>
                  </tr>
                  <tr>
                    <th>
                      <span>ニックネーム</span>
                    </th>
                    <td><%= current_user.nickname %></td>
                  </tr>
                  <tr>
                    <th>
                      <span>アバター</span>
                    </th>
                    <td><%= image_tag current_user.avatar.url, size: '50x50', class: 'rounded-circle mr15' %></td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="">
          <% @posts.each do |post| %>
            <span><%= post.user.email %></span>
            <p>タイトル</p>
            <span><%= post.title %></span>
            <p>評価</p>
            <span><%= post.star %></span>
            <p>レビュー</p>
            <span><%= post.review %></span><br>
            <span><%= link_to "編集", edit_post_path(post) %></span>
            <span><%= link_to "削除", post_path(post), method: :delete %></span><br>
          <% end %>
        </div>
        <!--他人のマイページ-->
        <%- else %>
        <p><%= @email %>さんのページ</p>
        <% content_for(:title, 'プロフィール') %>
        <div class="container pt-3">
          <div class="row">
            <div class="col-md-10 offset-md-1 mb-5">
              <h1 class="float-left"><%= t('.プロフィール') %></h1>
              
              </div>
              <div class="col-md-10 offset-md-1">
                <table class="table">
                  <tbody>
                    <tr>
                      <th>
                        <span>メールアドレス</span>
                      </th>
                      <td><%= current_user.email %></td>
                    </tr>
                    <tr>
                      <th>
                        <span>ニックネーム</span>
                      </th>
                      <td><%= current_user.nickname %></td>
                    </tr>
                    <tr>
                      <th>
                        <span>アバター</span>
                      </th>
                      <td><%= image_tag current_user.avatar.url, size: '50x50', class: 'rounded-circle mr15' %></td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <div class="">
            <% @posts.each do |post| %>
              <span><%= post.user.email %></span>
              <p>タイトル</p>
              <span><%= post.title %></span>
              <p>評価</p>
              <span><%= post.star %></span>
              <p>レビュー</p>
              <span><%= post.review %></span><br>
              <span><%= link_to "編集", edit_post_path(post) %></span>
              <span><%= link_to "削除", post_path(post), method: :delete %></span><br>
            <% end %>
    </main>
  </body>
</html>