config/routes.rb
Rails.application.routes.draw do
  
  get 'home/new' => 'home#new'
  post 'home' => 'home#create'
  get 'relationships/followings'
  get 'relationships/followers'
  
  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: "home#index"
 
  resources :posts, only: [:create, :new, :edit, :update, :destroy]
  resources :users, only: :show
  resource :profile, only: %i[show edit update]
  
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  scope '(:locale)' do
    resources :books
    resources :users, except: :create do
      member do
        get :followings, :followers
      end
    end
    resource :user_avatars, only: :destroy
    resources :relationships, only: %I[create destroy] # 追記
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  after_save :create_nickname
  
  def create_nickname
    @nickname = 'securerandom'
  end
  
  has_many :posts
  
  mount_uploader :avatar, ImageUploader
  
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # has_many :followers,
  #         class_name: 'Relationship',
  #         foreign_key: 'follower_id',
  #         dependent: :destroy,
  #         inverse_of: :follower
  # has_many :followings,
  #         class_name: 'Relationship',
  #         foreign_key: 'following_id',
  #         dependent: :destroy,
  #         inverse_of: :following
           
  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show
        @user = User.find(params[:id])
        @email = current_user.email
        @posts = current_user.posts
    end

    def followings
        @followings = @user.following_users
    end

    def followers
        @followers = @user.follower_users
    end
    
    private

    def set_user
        @user = User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/followers.html.erb
<h1><%= t("title.followers") %></h1>

<table>
  <% @followers.each do |users| %>
    <tr>
      <td>
        <% if user.avatar.attached? %>
          <%= image_tag user.avatar.variant(resize_to_limit: [30, 30]) %>
        <% end %>
      </td>
      <td><%= link_to user.nickname, user_path(user) %></td>
      <td><%= user.profile %></td>
    </tr>
  <% end %>
</table>

<%= link_to t("button.back"), user_path %>

app/views/users/followings.html.erb
<h1><%= t("title.followings") %></h1>

<table>
  <% @followings.each do |users| %>
    <tr>
      <td>
        <% if user.avatar.attached? %>
          <%= image_tag user.avatar.variant(resize_to_limit: [30, 30]) %>
        <% end %>
      </td>
      <td><%= link_to user.nickname, user_path(user) %></td>
      <td><%= user.profile %></td>
    </tr>
  <% end %>
</table>

<%= link_to t("button.back"), user_path %>

app/views/users/show.html.erb
<!DOCTYPE html>

  <body>
    <main class="bg-home">
      <!--ログイン本人のマイページ-->
      <%- if @user.id == @current_user.id %>
      <h3><%= current_user.nickname %>さんのページ</h3>
      <tr>
        <%=link_to "フォロー数: #{current_user.followings.count}", followings_user_path, class: 'btn btn-info' %>
        <%=link_to "フォロワー数: #{current_user.followers.count}", followers_user_path, class: 'btn btn-info' %>
      </tr>
      <!--プロフィール-->
      <% content_for(:title, 'プロフィール') %>
      <div class="container pt-3">
        <div class="row">
          <div class="col-md-10 mb-5">
            <h4 class="float-left"><%= t('.プロフィール') %></h4>
            <%=link_to "編集", edit_profile_path, class: 'btn btn-success float-right' %>
            </div>
            <div class="col-md-10">
              <table class="table">
                <tbody>
                  <tr>
                    <th>
                      <span>メールアドレス</span>
                    </th>
                    <td><%= current_user.email %></td>
                  </tr>
                  <tr>
                    <th>
                      <span>ニックネーム</span>
                    </th>
                    <td><%= current_user.nickname %></td>
                  </tr>
                  <tr>
                    <th>
                      <span>アバター</span>
                    </th>
                    <td><%= image_tag current_user.avatar.url, size: '50x50', class: 'rounded-circle mr15' %></td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <!--投稿一覧-->
        <div class="">
          <% @posts.each do |post| %>
            <span><%= post.user.nickname %></span>
            <p>タイトル</p>
            <span><%= post.title %></span>
            <p>評価</p>
            <span><%= post.star %></span>
            <p>レビュー</p>
            <span><%= post.review %></span><br>
            <span><%= link_to "編集", edit_post_path(post) %></span>
            <span><%= link_to "削除", post_path(post), method: :delete %></span><br>
          <% end %>
        </div>
        <!--他人のマイページ-->
        <%- else %>
          <p><%= @user.email %>さんのページ</p>
          <!--フォローボタン-->
          <% if current_user.following?(@user) %>
            <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(@user.id), method: :post %>
          <% end %>
          
          <% content_for(:title, 'プロフィール') %>
          <div class="container pt-3">
            <div class="row">
              <div class="col-md-10 offset-md-1 mb-5">
                <h1 class="float-left"><%= t('.プロフィール') %></h1>
                </div>
                <div class="col-md-10 offset-md-1">
                  <table class="table">
                    <tbody>
                      <tr>
                        <th>
                          <span>メールアドレス</span>
                        </th>
                        <td><%= @user.email %></td>
                      </tr>
                      <tr>
                        <th>
                          <span>ニックネーム</span>
                        </th>
                        <td><%= @user.nickname %></td>
                      </tr>
                      <tr>
                        <th>
                          <span>アバター</span>
                        </th>
                        <td><%= image_tag @user.avatar.url, size: '50x50', class: 'rounded-circle mr15' %></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <div class="">
              <% @user.posts.each do |post| %>
                <span><%= @user.nickname %></span>
                <p>タイトル</p>
                <span><%= post.title %></span>
                <p>評価</p>
                <span><%= post.star %></span>
                <p>レビュー</p>
                <span><%= post.review %></span><br>
              <% end %>
        <% end %>
    </main>
  </body>
</html>